COPY = {
    "title": "商品视觉工作台",
    "subtitle": "从观察到重构，每一步都有依据。",
    "fixture": "默认 Fixture · 本地保存 · 真实调用逐次确认",
    "fixture_note": "Fixture 只验证流程。真实适配器已接入，尚待真实样例验证；选择真实模式后须逐次确认外发和费用。",
    "pattern": "未经版师验证，不可直接裁剪生产",
    "states": {
        "queued": "排队中",
        "running": "执行中",
        "succeeded": "已完成",
        "failed": "失败",
        "interrupted": "已中断",
        "outcome_unknown": "结果未知",
    },
    "modes": {
        "CHECK": "AI 对照检查",
        "A": "逆推完整提示词",
        "A_white": "生成白背景实物图",
        "A_views": "生成说明书草图（三视图）· Beta",
        "CUTOUT": "本地抠图 · 透明 PNG",
        "A_front": "正面技术图候选",
        "A_back": "背面技术图候选",
        "A_pattern": "实验性纸样示意",
        "B1": "主体保留合成",
        "B2": "一键混图",
        "C_analyze": "解析参考图",
        "C1": "直接参考基线",
        "C2": "可控配方重构",
    },
    "evidence": {
        "user_confirmed": "用户确认",
        "observed": "图像观察（仍需核验）",
        "inferred": "设计推测",
        "unknown": "未知",
    },
    "checks": ["轮廓", "颜色", "文字 / Logo", "图案纹理", "部件与结构"],
    "analysis_note": "Fixture 未识别输入内容，字段默认未知。用户填写后可标记“用户确认”。",
    "recipe_note": "摄影信息为视觉估计，留空表示 unknown。先保存配方，再运行 C2。",
    "redraw_note": "直接上传完整原图，无需抠图。描述要替换的背景和道具；默认要求保留商品本体、Logo 和文字，生成后请对照检查细节。",
    "composite_note": "使用透明 PNG 或同尺寸黑白蒙版（白色保留）。当前不支持自动抠图；支持本地投影，主体光照不重绘。",
}
